// USER CONSTANTS
export const USER_LOGIN_REQUEST = "USER_LOGIN_REQUEST";
export const USER_LOGIN_SUCCESS = "USER_LOGIN_SUCCESS";
export const USER_LOGIN_FAILURE = "USER_LOGIN_FAILURE";
export const USER_LOGOUT_REQUEST = "USER_LOGOUT_REQUEST";

// CONNECTION CONSTANTS
export const CHECKING_CONNECTION = "CHECKING_CONNECTION";

//ORDER CONSTANTS
export const ORDER_FETCH_REQUEST = "ORDER_FETCH_REQUEST";
export const ORDER_FETCH_SUCCESS = "ORDER_FETCH_SUCCESS";
export const ORDER_FETCH_FAILURE = "ORDER_FETCH_FAILURE";
